"""
Kompose - CLI for managing Docker Compose services.

Usage:
    kompose <command> [options]

Top-level (daily ergonomics):
    up           Start services             (alias: service up)
    down         Stop services              (alias: service down)
    restart   r  Restart services           (alias: service restart)
    logs      l  View service logs          (alias: service logs)
    status    st Show services status       (alias: service status)
    check        Lint compose files and env drift
    fix          Auto-fix (compose-level rules + interactive env sync)
                   --auto  : only compose-level auto-fixes
                   --env   : only interactive env sync
    upgrade      Trigger image updates via watchtower's HTTP API
                   --logs  : render the latest session, no trigger

Canonical noun-verb form:
    service [svc] up|down|restart|logs|status
"""

import argparse
import sys

from kompose import __version__
from kompose.compose import cmd_down, cmd_logs, cmd_restart, cmd_up
from kompose.config import DEFAULT_HOST
from kompose.fix import cmd_fix
from kompose.lint import cmd_check
from kompose.status import cmd_status
from kompose.upgrade import cmd_upgrade
from kompose.utils import init_colors


# Zsh helpers injected into the generated completion script (via shtab's
# `preamble`). They mirror the runtime path resolution: `$WORKSPACE_DIR/$HOST`
# are read from the environment if set, else fall back to the same defaults
# the CLI uses (`/mnt/home/thomas/workspace/homelab` and `nas`).
_ZSH_PREAMBLE = r"""
# --- kompose completion helpers (regenerated by `kompose --completion zsh`) ---

_kompose_workspace() {
  print -r -- "${KOMPOSE_WORKSPACE:-/mnt/home/thomas/workspace/homelab}"
}

_kompose_host_dir() {
  # Honor `--host <name>` if it appears earlier in the command line, else KOMPOSE_HOST, else nas.
  local i host="${KOMPOSE_HOST:-nas}"
  for (( i = 2; i < CURRENT; i++ )); do
    if [[ ${words[i]} == "--host" && -n ${words[i+1]} ]]; then
      host=${words[i+1]}
    fi
  done
  print -r -- "$host"
}

_kompose_services() {
  local ws="$(_kompose_workspace)"
  local host="$(_kompose_host_dir)"
  [[ -d $ws/$host ]] || return
  local -a names
  names=(${ws}/${host}/*(/N:t))
  _describe 'service' names
}

_kompose_hosts() {
  local ws="$(_kompose_workspace)"
  [[ -d $ws ]] || return
  local -a names
  names=(${ws}/*(/N:t))
  _describe 'host' names
}

_kompose_containers() {
  local ws="$(_kompose_workspace)"
  local host="$(_kompose_host_dir)"
  # Previous word is the group; its compose.yml holds the container names.
  local service="${words[CURRENT-1]}"
  local compose="$ws/$host/$service/compose.yml"
  [[ -f $compose ]] || return
  local -a names
  names=(${(f)"$(awk '
    /^services:[[:space:]]*$/ { in_svc=1; next }
    in_svc && /^[^[:space:]]/  { in_svc=0 }
    in_svc && /^  [a-zA-Z_-]/  { sub(/:.*$/, ""); sub(/^[[:space:]]+/, ""); print }
  ' "$compose")"})
  _describe 'container' names
}
"""


# ---------------------------------------------------------------------------
# Arg helpers — keep the same shape for top-level aliases and canonical forms
# ---------------------------------------------------------------------------


# shtab `.complete` hints: when the user TABs at one of these positions, the
# generated zsh script calls the named function (defined in _ZSH_PREAMBLE).
_COMPLETE_SERVICE = {"zsh": "_kompose_services"}
_COMPLETE_CONTAINER = {"zsh": "_kompose_containers"}
_COMPLETE_HOST = {"zsh": "_kompose_hosts"}


def _add_lifecycle_args(parser: argparse.ArgumentParser) -> None:
    """Args shared by up/down/restart: <service> + <containers...>."""
    parser.add_argument("service", nargs="?", metavar="<service>", help="Service (group dir) or docker compose service name").complete = _COMPLETE_SERVICE
    parser.add_argument("containers", nargs="*", metavar="<container>", help="Specific containers within the service").complete = _COMPLETE_CONTAINER


def _add_logs_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("service", metavar="<service>", help="Service to view logs").complete = _COMPLETE_SERVICE
    parser.add_argument("containers", nargs="*", metavar="<container>", help="Specific containers within the service").complete = _COMPLETE_CONTAINER
    parser.add_argument("-f", "--follow", action="store_true", default=True, help="Follow log output (default)")
    parser.add_argument("--no-follow", action="store_false", dest="follow", help="Don't follow log output")
    parser.add_argument("-n", "--tail", default="100", metavar="N", help="Number of lines to show (default: 100)")


def _add_status_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("service", nargs="?", metavar="<service>", help="Drill into a specific service: filter the table and tail its logs").complete = _COMPLETE_SERVICE
    parser.add_argument("-s", "--stats", action="store_true", help="Show CPU and memory usage")
    parser.add_argument("-n", "--tail", default="30", metavar="N", help="Lines of log to show when drilling into a service (default: 30)")
    parser.add_argument("-f", "--follow", action="store_true", help="Live mode — with a service arg: follow logs after the tail; without: refresh the table every -i seconds")
    parser.add_argument("-i", "--interval", type=int, default=2, metavar="N", help="Refresh interval in seconds for live mode (default: 2)")
    parser.add_argument("--no-logs", action="store_true", help="Suppress the log tail when drilling into a service")


def _add_check_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("service", nargs="?", metavar="<service>", help="Service to check (default: all)").complete = _COMPLETE_SERVICE


def _add_fix_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("service", nargs="?", metavar="<service>", help="Service to fix (default: all)").complete = _COMPLETE_SERVICE
    parser.add_argument("-f", "--force", action="store_true", help="Skip confirmation, apply defaults")
    parser.add_argument("--dry-run", action="store_true", help="Preview what would change without applying")
    scope = parser.add_mutually_exclusive_group()
    scope.add_argument("--auto", action="store_true", help="Only run compose-level auto-fixes (skip the interactive env sync)")
    scope.add_argument("--env", action="store_true", help="Only run the interactive env sync (skip compose-level rule fixes)")


def _add_upgrade_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("service", nargs="?", metavar="<service>", help="Service group to upgrade (default: all containers)").complete = _COMPLETE_SERVICE
    parser.add_argument("-f", "--force", action="store_true", help="Skip confirmation on the global form")
    parser.add_argument("--logs", action="store_true", help="Render the latest watchtower session (no trigger)")


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="kompose",
        description="CLI for managing Docker Compose services",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=f"""
Examples:
  kompose up                    Start all services (host: {DEFAULT_HOST})
  kompose up paperless          Start a single service (or expand a group)
  kompose down servarr plex     Stop a specific container inside a group
  kompose restart immich        (alias: kompose r immich)
  kompose logs paperless -n 50  (alias: kompose l paperless -n 50)
  kompose st                    Rich table of all services (alias of `status`)
  kompose status traefik        Filtered table + last 30 log lines
  kompose status traefik -f     Same, follow logs continuously
  kompose check                 Run every lint rule (compose + env)
  kompose fix                   Apply all fixes (compose + interactive env sync)
  kompose fix --auto            Only compose-level auto-fixes (no env prompts)
  kompose fix --env             Only interactive env sync
  kompose fix --dry-run         Preview only
  kompose upgrade               Trigger watchtower update on every container
  kompose upgrade paperless     Same, scoped to one group's images
  kompose upgrade --logs        Show the latest watchtower session
  kompose service status        Canonical form of `kompose status`

Host override:
  kompose --host other up       Use different host directory
""",
    )
    parser.add_argument("-v", "--version", action="version", version=f"%(prog)s {__version__}")
    parser.add_argument("--no-color", action="store_true", help="Disable colored output")
    parser.add_argument("--host", metavar="HOST", default=None, help=f"Host directory (default: {DEFAULT_HOST})").complete = _COMPLETE_HOST
    parser.add_argument("--completion", choices=["zsh"], metavar="SHELL", help="Print a shell completion script to stdout and exit")

    subparsers = parser.add_subparsers(dest="command", metavar="<command>")

    # ---- Top-level aliases (lifecycle) ----
    p = subparsers.add_parser("up", help="Start services (alias of: service up)")
    _add_lifecycle_args(p)
    p.set_defaults(func=cmd_up)

    p = subparsers.add_parser("down", help="Stop services (alias of: service down)")
    _add_lifecycle_args(p)
    p.set_defaults(func=cmd_down)

    p = subparsers.add_parser("restart", aliases=["r"], help="Restart services (alias of: service restart)")
    _add_lifecycle_args(p)
    p.set_defaults(func=cmd_restart)

    p = subparsers.add_parser("logs", aliases=["l"], help="View service logs (alias of: service logs)")
    _add_logs_args(p)
    p.set_defaults(func=cmd_logs)

    p = subparsers.add_parser("status", aliases=["st"], help="Show services status (alias of: service status)")
    _add_status_args(p)
    p.set_defaults(func=cmd_status)

    # ---- Top-level globals ----
    p = subparsers.add_parser("check", help="Lint compose files and env drift")
    _add_check_args(p)
    p.set_defaults(func=cmd_check)

    p = subparsers.add_parser("fix", help="Apply fixes (compose auto-fixes + interactive env sync). Scope: --auto or --env.")
    _add_fix_args(p)
    p.set_defaults(func=cmd_fix)

    p = subparsers.add_parser("upgrade", help="Trigger image updates via watchtower's HTTP API")
    _add_upgrade_args(p)
    p.set_defaults(func=cmd_upgrade)

    # ---- Canonical noun: service ----
    service_parser = subparsers.add_parser("service", aliases=["svc"], help="Service lifecycle (canonical noun-verb form)")
    service_subparsers = service_parser.add_subparsers(dest="service_command", metavar="<verb>")

    sp = service_subparsers.add_parser("up", help="Start services")
    _add_lifecycle_args(sp)
    sp.set_defaults(func=cmd_up)

    sp = service_subparsers.add_parser("down", help="Stop services")
    _add_lifecycle_args(sp)
    sp.set_defaults(func=cmd_down)

    sp = service_subparsers.add_parser("restart", aliases=["r"], help="Restart services")
    _add_lifecycle_args(sp)
    sp.set_defaults(func=cmd_restart)

    sp = service_subparsers.add_parser("logs", aliases=["l"], help="View service logs")
    _add_logs_args(sp)
    sp.set_defaults(func=cmd_logs)

    sp = service_subparsers.add_parser("status", aliases=["st"], help="Show services status with IPs")
    _add_status_args(sp)
    sp.set_defaults(func=cmd_status)

    # ---- Dispatch ----
    args = parser.parse_args()

    if args.completion:
        import shtab
        sys.stdout.write(shtab.complete(parser, shell=args.completion, preamble={"zsh": _ZSH_PREAMBLE}))
        return 0

    init_colors(args.no_color)

    if args.command is None:
        parser.print_help()
        return 0

    if args.command in ("service", "svc") and getattr(args, "service_command", None) is None:
        service_parser.print_help()
        return 0

    if hasattr(args, "func"):
        return args.func(args)

    parser.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
