"""Shared CLI plumbing — zsh preamble helpers, completion hints, subparser util.

The bits in this module are needed by more than one cli/<command>.py module
(workspace resolution, service/container completion, the help-mirror subparser
helper). Per-command CLI wiring lives in its own cli/<name>.py module.
"""

from __future__ import annotations

import argparse


# Mirrors the runtime path resolution (`$WORKSPACE_DIR/$HOST`) using the same
# env-var precedence the Python CLI uses, so completion stays accurate even
# when the user temporarily overrides `KOMPOSE_HOST` or `KOMPOSE_WORKSPACE`.
ZSH_PREAMBLE = r"""
# --- kompose completion helpers (regenerated by `kompose --completion zsh`) ---

_kompose_workspace() {
  print -r -- "${KOMPOSE_WORKSPACE:-/mnt/home/thomas/workspace/homelab}"
}

_kompose_host_dir() {
  # Honor `--host <name>` if it appears earlier in the command line, else KOMPOSE_HOST, else nas.
  local i host="${KOMPOSE_HOST:-nas}"
  for (( i = 2; i < CURRENT; i++ )); do
    if [[ ${words[i]} == "--host" && -n ${words[i+1]} ]]; then
      host=${words[i+1]}
    fi
  done
  print -r -- "$host"
}

_kompose_services() {
  local ws="$(_kompose_workspace)"
  local host="$(_kompose_host_dir)"
  [[ -d $ws/$host ]] || return
  local -a names
  names=(${ws}/${host}/*(/N:t))
  _describe 'service' names
}

_kompose_hosts() {
  local ws="$(_kompose_workspace)"
  [[ -d $ws ]] || return
  local -a names
  names=(${ws}/*(/N:t))
  _describe 'host' names
}

_kompose_containers() {
  local ws="$(_kompose_workspace)"
  local host="$(_kompose_host_dir)"
  # Previous word is the group; its compose.yml holds the container names.
  local service="${words[CURRENT-1]}"
  local compose="$ws/$host/$service/compose.yml"
  [[ -f $compose ]] || return
  local -a names
  names=(${(f)"$(awk '
    /^services:[[:space:]]*$/ { in_svc=1; next }
    in_svc && /^[^[:space:]]/  { in_svc=0 }
    in_svc && /^  [a-zA-Z_-]/  { sub(/:.*$/, ""); sub(/^[[:space:]]+/, ""); print }
  ' "$compose")"})
  _describe 'container' names
}
"""


# shtab `.complete` hints: when the user TABs at one of these positions, the
# generated zsh script calls the named function (defined in ZSH_PREAMBLE).
COMPLETE_SERVICE = {"zsh": "_kompose_services"}
COMPLETE_CONTAINER = {"zsh": "_kompose_containers"}
COMPLETE_HOST = {"zsh": "_kompose_hosts"}


def add_subparser(subparsers, name: str, help: str, **kwargs) -> argparse.ArgumentParser:
    """Create a subparser with `help=` mirrored into `description=`.

    argparse stores `help=` on the subparser *action*, not on the subparser
    itself. shtab reads `parser.description` when building the zsh `_commands`
    table — without this mirror, command rows render as `name:` (empty
    description), which collapses the nice two-column `_describe` layout.
    """
    return subparsers.add_parser(name, help=help, description=help, **kwargs)
